### ISSUE TITLE
Dependency on forwardable not covered

### ISSUE THREAD

**Issue by MikeFlint** [johnnyshields/naturalsort#1]
Running on its own, fails to load due to 'forwardable' being missing:

```
$ sudo gem install naturalsort 
Fetching: naturalsort-1.2.0.gem (100%)
Successfully installed naturalsort-1.2.0
1 gem installed

$ irb
irb(main):001:0> require 'natural_sort'
NameError: uninitialized constant Module::Forwardable
from /var/lib/gems/2.1.0/gems/naturalsort-1.2.0/lib/natural_sort/base.rb:16:in `singleton class'
from /var/lib/gems/2.1.0/gems/naturalsort-1.2.0/lib/natural_sort/base.rb:15:in `<module:NaturalSort>'
from /var/lib/gems/2.1.0/gems/naturalsort-1.2.0/lib/natural_sort/base.rb:13:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /var/lib/gems/2.1.0/gems/naturalsort-1.2.0/lib/natural_sort.rb:4:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
from (irb):1
from /usr/bin/irb:11:in `<main>'
irb(main):002:0> exit

$ echo  "require 'natural_sort'" > testns.rb
$ cat testns.rb 
require 'natural_sort'
$ ruby testns.rb
/var/lib/gems/2.1.0/gems/naturalsort-1.2.0/lib/natural_sort/base.rb:16:in `singleton class': uninitialized constant Module::Forwardable (NameError)
from /var/lib/gems/2.1.0/gems/naturalsort-1.2.0/lib/natural_sort/base.rb:15:in `<module:NaturalSort>'
from /var/lib/gems/2.1.0/gems/naturalsort-1.2.0/lib/natural_sort/base.rb:13:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /var/lib/gems/2.1.0/gems/naturalsort-1.2.0/lib/natural_sort.rb:4:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
from testns.rb:1:in `<main>'
```

Adding "require 'forwardable'" to natural_sort.rb fixes issue.

**Comment by johnnyshields** [comment]
Fixed this one, thanks.
